# Generated by Django 4.2.20 on 2025-04-15 13:24

import core.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='Category',
            new_name='category',
        ),
        migrations.RemoveField(
            model_name='product',
            name='image',
        ),
        migrations.RemoveField(
            model_name='vendor',
            name='image',
        ),
        migrations.AddField(
            model_name='product',
            name='product_image',
            field=models.ImageField(default='product.png', upload_to=core.models.user_directory_path),
        ),
        migrations.AddField(
            model_name='vendor',
            name='vendor_image',
            field=models.ImageField(default='vendor.png', upload_to=core.models.user_directory_path),
        ),
        migrations.AlterField(
            model_name='category',
            name='image',
            field=models.ImageField(default='category.png', upload_to=core.models.user_directory_path),
        ),
        migrations.AlterField(
            model_name='productimage',
            name='image',
            field=models.ImageField(default='productimage.png', upload_to=core.models.user_directory_path),
        ),
        migrations.AlterField(
            model_name='vendor',
            name='authentication',
            field=models.ImageField(upload_to=core.models.user_directory_path),
        ),
    ]
